# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=1.4.0
group=xyz.faewulf.lib
java_version=25
# Common
minecraft_version=26.1.2
minecraft_version_max=26.2
mod_name=Faewulf's Lib
mod_author=Faewulf
mod_id=faewulf_lib
license=CC-BY-NC-SA-4.0
credits=
description=A library mod that provides utility functions and methods commonly used across my (Faewulf) mods.
minecraft_version_range=[26.1.2, 26.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1
mdg_version=2.0.141
# Fabric api
fabric_version=0.148.0+26.1.2
fabric_loader_version=0.19.2
loom_version=1.15.5
# Forge
forge_version=61.0.1
forge_loader_version_range=[61,)
forge_gradle_version=[6.0.46,6.2)
# NeoForge
neoforge_version=26.1.2.7-beta
neoforge_loader_version_range=[6,)
# Lib
mod_menu_version=18.0.0
# Gradle
org.gradle.jvmargs=-Xmx8G -Xms1G -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=false
#publish
# confirm for real publish
confirm_publish=false
modrinth_id=q4N9H96q
curseforge_id=1209568
# release, beta, alpha
version_type=release
