# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.4.0
group=xyz.faewulf.lib
java_version=25

# Common
minecraft_version=26.2
minecraft_version_max=26.3
mod_name=Faewulf's Lib
mod_author=Faewulf
mod_id=faewulf_lib
license=CC-BY-NC-SA-4.0
credits=
description=A library mod that provides utility functions and methods commonly used across my (Faewulf) mods.
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1
mdg_version=2.0.141

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3
loom_version=1.16.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[4,)

# Lib
mod_menu_version=20.0.1
# Gradle
org.gradle.jvmargs=-Xmx8G -Xms1G -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false
#publish
# confirm for real publish
confirm_publish=false
modrinth_id=q4N9H96q
curseforge_id=1209568
# release, beta, alpha
version_type=release

